runtime: go
env: flex
service_account: {{YOUR_SERVICE_ACCOUNT_EMAIL}}

runtime_config:
    operating_system: ubuntu22
    runtime_version: "1.20"

liveness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

env_variables:
  BIGTABLE_INSTANCE_ID: {{YOUR_BIGTABLE_INSTANCE_ID}}
  GCP_PROJECT_ID: {{YOUR_GCP_PROJECT_ID}}
  REALM_ID: {{YOUR_REALM_ID}}
  PROVIDER: gcp
