version: "3.9"
services:
  jb-sw-realm:
    build: .
    restart: always
    ports:
      - "443:443"
    environment:
      REALM_ID: f6fa9265-c07e-4614-9474-898e370dd33e
      PROVIDER: memory
      DISABLE_TLS:
      BIGTABLE_INSTANCE_ID:
      GCP_PROJECT_ID:
      AWS_REGION_NAME:
      MONGO_URL:
      TENANT_SECRETS: '{"test":{"1":"an-auth-token-key"}}'
      LETS_ENCRYPT_CACHE: /var/cache/letsencrypt
    volumes:
      - /var/cache/letsencrypt:/var/cache/letsencrypt
