name: Lint and Test

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  lint_and_test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.4"
          check-latest: false

      - name: Run revive
        run: |
          go install github.com/mgechev/revive@latest
          revive -config revive.toml -formatter friendly ./...

      - name: Run staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...

      - name: Run govulncheck
        run: |
          go version
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

      - name: Run go test
        run: go test -v ./...

      - name: Build Executables
        run: |
          go build ./cmd/jb-sw-realm
          go build ./cmd/tenant_log

      - name: Run go mod tidy
        run: go mod tidy && git diff --quiet
